#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php'))
{
	require __DIR__.'/vendor/autoload.php';
}
else
{
	require __DIR__.'/../../autoload.php';
}

function homestead_path()
{
	return ( isset($_SERVER['HOME']) ? $_SERVER['HOME'] : $_SERVER['HOMEDRIVE'] . $_SERVER['HOMEPATH'] ) . DIRECTORY_SEPARATOR . '.homestead';
}

$app = new Symfony\Component\Console\Application('Laravel Homestead', '2.0.0');

$app->add(new Laravel\Homestead\DestroyCommand);
$app->add(new Laravel\Homestead\EditCommand);
$app->add(new Laravel\Homestead\HaltCommand);
$app->add(new Laravel\Homestead\InitCommand);
$app->add(new Laravel\Homestead\ResumeCommand);
$app->add(new Laravel\Homestead\UpCommand);
$app->add(new Laravel\Homestead\UpdateCommand);
$app->add(new Laravel\Homestead\SshCommand);
$app->add(new Laravel\Homestead\StatusCommand);
$app->add(new Laravel\Homestead\SuspendCommand);

$app->run();
